Models/Medico.cs
using System.ComponentModel.DataAnnotations;

namespace RecepcionMedica.Models;

    public class Medico
    {
        public int Id { get; set; }
    
        public string? NombreCompleto { get; set; }

        public int Edad { get; set; }

        public int Calificacion { get; set; }

<<<<<<< HEAD
        public int EspecialidadId { get; set; } // Required foreign key property
        public Especialidad? Especialidad { get; set; } // Required reference navigation to principal

        public ICollection<Paciente> Pacientes { get; } = new List<Paciente>();
=======

          public int EspecialidadId { get; set; } // Required foreign key property
          [Display(Name = "Especialidad")]
        public Especialidad? Especialidad { get; set; } // Required reference navigation to principal

        public ICollection<Paciente> Pacientes { get; } = new List<Paciente>();

        public string? Profesión => Especialidad?.NombreEspecialidad;
>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581
    }

ViewModels/MedicoViewModel.cs
using RecepcionMedica.Models;

namespace recepcionMedica.ViewModels;

public class MedicoViewModel
{
    public List<Medico> Medicos { get; set;} = new List<Medico>{};

    public string? NameFilter { get; set;}

}

ViewModels/MedicosViewModel.cs
using RecepcionMedica.Models;

namespace recepcionMedica.ViewModels;

public class MedicosViewModel 
{

  public int Id { get; set; }
  public string? NombreCompleto { get; set; }

          public int Edad { get; set; }

        public int Calificacion { get; set; }

      public string? Profesion { get; set; }

      public ICollection<Paciente> Pacientes { get; set; } = new List<Paciente>();

}

Controllers/MedicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecepcionMedica.Data;
using RecepcionMedica.Models;
using recepcionMedica.ViewModels;

namespace RecepcionMedica.Controllers
{
    public class MedicoController : Controller
    {
        private readonly MvcMedicoContext _context;

        public MedicoController(MvcMedicoContext context)
        {
            _context = context;
        }

        // GET: Medico

        public async Task<IActionResult> Index(string NameFilter)
        {
<<<<<<< HEAD
            var mvcMedicoContext = _context.Medico.Include(m => m.Especialidad);
            return View(await mvcMedicoContext.ToListAsync());
=======
            try
            {
            var query = from Medico in _context.Medico.Include(p => p.Especialidad) select Medico;

            if (!string.IsNullOrEmpty(NameFilter)) {
                query = query.Where(x => x.NombreCompleto.ToLower().Contains(NameFilter.ToLower()) ||
                x.Especialidad.NombreEspecialidad.ToLower().Contains(NameFilter.ToLower()) ||
                x.Edad.ToString() == NameFilter ||
                x.Calificacion.ToString() == NameFilter);
            }

            var model =new MedicoViewModel();

            model.Medicos = await query.ToListAsync();

            return View(model);

            }
              catch(Exception ex) {

              return View("Error");
              }
          {
        }
>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581
        }

        // GET: Medico/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Medico == null)
            {
                return NotFound();
            }

            var medico = await _context.Medico
                .Include(m => m.Especialidad)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medico == null)
            {
                return NotFound();
            }
            var query = from Paciente in _context.Paciente.Include(p => p.Medico) where Paciente.MedicoId == id select Paciente;

            var viewModel = new MedicosViewModel();

            viewModel.NombreCompleto = medico.NombreCompleto;
            viewModel.Edad = medico.Edad;
            viewModel.Calificacion = medico.Calificacion;
            viewModel.Profesion = medico.Profesión;
            viewModel.Pacientes = await query.ToListAsync();
            viewModel.Id = medico.Id;

            return View(viewModel);
        }

        // GET: Medico/Create
        public IActionResult Create()
        {
<<<<<<< HEAD
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Id");
=======
            //ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Id");
            ViewData["Profesión"] = new SelectList(_context.Especialidad, "Id", "NombreEspecialidad");

>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581
            return View();
        }

        // POST: Medico/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
<<<<<<< HEAD
        public async Task<IActionResult> Create([Bind("Id,NombreCompleto,Edad,Calificacion,EspecialidadId")] Medico medico)
=======
        public async Task<IActionResult> Create([Bind("Id,NombreCompleto,Edad,Calificacion,EspecialidadId,Profesión")] Medico medico)
>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581
        {
            if (ModelState.IsValid)
            {
                _context.Add(medico);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Id", medico.EspecialidadId);
            return View(medico);
        }

        // GET: Medico/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Medico == null)
            {
                return NotFound();
            }

            var medico = await _context.Medico.FindAsync(id);
            if (medico == null)
            {
                return NotFound();
            }
<<<<<<< HEAD
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Id", medico.EspecialidadId);
=======
            ViewData["Profesión"] = new SelectList(_context.Especialidad, "Id", "NombreEspecialidad");
>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581
            return View(medico);
        }

        // POST: Medico/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NombreCompleto,Edad,Calificacion,EspecialidadId")] Medico medico)
        {
            if (id != medico.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medico);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicoExists(medico.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Id", medico.EspecialidadId);
            return View(medico);
        }

        // GET: Medico/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Medico == null)
            {
                return NotFound();
            }

            var medico = await _context.Medico
                .Include(m => m.Especialidad)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medico == null)
            {
                return NotFound();
            }
            
            return View(medico);
        }

        // POST: Medico/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Medico == null)
            {
                return Problem("Entity set 'MvcMedicoContext.Medico'  is null.");
            }
            var medico = await _context.Medico.FindAsync(id);
            if (medico != null)
            {
                _context.Medico.Remove(medico);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedicoExists(int id)
        {
          return (_context.Medico?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Medico/Create.cshtml
@model RecepcionMedica.Models.Medico

@{
    ViewData["Title"] = "Create";
}

<h1 style="text-align:center; font-family: 'Lobster', cursive; font-size: 32px; font-weight: bold;color: #1A5276;">Menu de Alta</h1>

<h4>Nuevo Médico</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreCompleto" class="control-label"></label>
                <input asp-for="NombreCompleto" class="form-control" />
                <span asp-validation-for="NombreCompleto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Calificacion" class="control-label"></label>
                <input asp-for="Calificacion" class="form-control" />
                <span asp-validation-for="Calificacion" class="text-danger"></span>
            </div>
            <!--<div class="form-group">
                <label asp-for="EspecialidadId" class="control-label"></label>
                <select asp-for="EspecialidadId" class ="form-control" asp-items="ViewBag.EspecialidadId"></select>
            </div> --->
            <div class="form-group">
                <label asp-for="Profesión" class="control-label"></label>
                <select asp-for="EspecialidadId" class ="form-control" asp-items="ViewBag.Profesión"></select>
            </div>
            <div class="form-group">
<<<<<<< HEAD
                <label asp-for="EspecialidadId" class="control-label"></label>
                <select asp-for="EspecialidadId" class ="form-control" asp-items="ViewBag.EspecialidadId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
=======
                <input type="submit" value="Dar de Alta" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-secondary">Volver al Indice</a>
>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Medico/Delete.cshtml
@model RecepcionMedica.Models.Medico

@{
    ViewData["Title"] = "Delete";
}

<h1 style="text-align:center; font-family: 'Lobster', cursive; font-size: 32px; font-weight: bold;color: #1A5276;">Esta seguro que desea eliminar el Médico?</h1>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCompleto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Calificacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Calificacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Especialidad)
        </dt>
        <dd class = "col-sm-10">
<<<<<<< HEAD
            @Html.DisplayFor(model => model.Especialidad.Id)
=======
            @Html.DisplayFor(model => model.Especialidad.NombreEspecialidad)
>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar Medico" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Volver al Indice</a>
    </form>
</div>

Views/Medico/Details.cshtml
@using recepcionMedica.ViewModels;

@model MedicosViewModel;

@{
    ViewData["Title"] = "Details";
}

<h1 style="text-align:center; font-family: 'Lobster', cursive; font-size: 32px; font-weight: bold;color: #1A5276;">Detalle</h1>

<div>
    <h4>Medico</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCompleto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Calificacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Calificacion)
        </dd>
        <dt class = "col-sm-2">
<<<<<<< HEAD
            @Html.DisplayNameFor(model => model.Especialidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Especialidad.Id)
=======
            @Html.DisplayNameFor(model => model.Profesion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Profesion)
>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581
        </dd>
    </dl>
        <div>
            <h2>Lista de pacientes</h2>
            <ol>
                @foreach (var item in Model.Pacientes)
                {
                    <li>@item.NombreCompleto</li>
                }
            </ol>
        </div>
</div>
<div>
    <a asp-action="Index" class="btn btn-secondary">Volver al Indice</a>
</div>

Views/Medico/Edit.cshtml
@model RecepcionMedica.Models.Medico

@{
    ViewData["Title"] = "Edit";
}

<h1 style="text-align:center; font-family: 'Lobster', cursive; font-size: 32px; font-weight: bold;color: #1A5276;">Editar Médico</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NombreCompleto" class="control-label"></label>
                <input asp-for="NombreCompleto" class="form-control" />
                <span asp-validation-for="NombreCompleto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Calificacion" class="control-label"></label>
                <input asp-for="Calificacion" class="form-control" />
                <span asp-validation-for="Calificacion" class="text-danger"></span>
            </div>
            <div class="form-group">
<<<<<<< HEAD
                <label asp-for="EspecialidadId" class="control-label"></label>
                <select asp-for="EspecialidadId" class="form-control" asp-items="ViewBag.EspecialidadId"></select>
                <span asp-validation-for="EspecialidadId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
=======
                <label asp-for="Profesión" class="control-label"></label>
                <select asp-for="EspecialidadId" class ="form-control" asp-items="ViewBag.Profesión"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Volver al Indice</a>
>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Medico/Index.cshtml
@using recepcionMedica.ViewModels;

@model MedicoViewModel;

@{
    ViewData["Title"] = "Index";
}

<head>
    <link rel="stylesheet" href="/css/style.css">
    <style>
    body {
        background-color: #E0FFFF;
    }
</style>
</head>

<h1 style="text-align:center; font-family: 'Lobster', cursive; font-size: 32px; font-weight: bold;color: #1A5276;">Índice de Médicos</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Dar de alta Nuevo Médico</a>
</p>

<div class="row">
    <form method="get" asp-action="Index" asp-controller="Medico">
        <div class="rec form-group">
            <input class ="form-control" asp-for="NameFilter">
        </div>
        <button class="btn btn-secondary" type="submit">Buscar</button>
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Medicos.FirstOrDefault().NombreCompleto)
            </th>
            <th>
<<<<<<< HEAD
                @Html.DisplayNameFor(model => model.Edad)
=======
                @Html.DisplayNameFor(model => model.Medicos.FirstOrDefault().Edad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicos.FirstOrDefault().Calificacion)
>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicos.FirstOrDefault().Profesión)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Especialidad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Medicos) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCompleto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Calificacion)
            </td>
            <td>
<<<<<<< HEAD
                @Html.DisplayFor(modelItem => item.Especialidad.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
=======
                @Html.DisplayFor(modelItem => item.Profesión)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Borrar</a>
>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581
            </td>
        </tr>
}
    </tbody>
</table>