Models/Paciente.cs
namespace RecepcionMedica.Models;

    public class Paciente
    {
        public int Id { get; set; }
    
        public string? NombreCompleto { get; set; }

<<<<<<< HEAD
        public string? Sexo { get; set; }
=======
        public SexoEnum Sexo { get; set; }
>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581

        public string? ObraSocial { get; set; }

        public int Edad { get; set; }

        public int telefono { get; set; }

        public int MedicoId { get; set; } // Required foreign key property
        public Medico? Medico { get; set; } // Required reference navigation to principal
<<<<<<< HEAD
=======

        public string? MedicoTratante => Medico?.NombreCompleto;
>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581
    }

ViewModels/PacienteViewModel.cs
using RecepcionMedica.Models;

namespace recepcionMedica.ViewModels;

public class PacienteViewModel
{
    public List<Paciente> Pacientes { get; set;} = new List<Paciente>{};

    public string? NameFilter { get; set;}

}

Controllers/PacienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecepcionMedica.Data;
using RecepcionMedica.Models;
using recepcionMedica.ViewModels;

namespace recepcionMedica.Controllers
{
    public class PacienteController : Controller
    {
        private readonly MvcMedicoContext _context;

        public PacienteController(MvcMedicoContext context)
        {
            _context = context;
        }

        // GET: Paciente
        public async Task<IActionResult> Index(string NameFilter)
        {
            try
            {
            var query = from Paciente in _context.Paciente.Include(p => p.Medico) select Paciente;

            if (!string.IsNullOrEmpty(NameFilter)) {
                query = query.Where(x => x.NombreCompleto.ToLower().Contains(NameFilter.ToLower()) ||
                x.Medico.NombreCompleto.ToLower().Contains(NameFilter.ToLower()) ||
                x.Edad.ToString() == NameFilter ||
                x.ObraSocial.ToLower().Contains(NameFilter.ToLower()));
                //x.Sexo.ToString() == NameFilter);
            }

            var model =new PacienteViewModel();

            model.Pacientes = await query.ToListAsync();

            return View(model);

            }
              catch(Exception ex) {

              return View("Error");
              }
          {
        }
        }

        // GET: Paciente/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Paciente == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente
                .Include(p => p.Medico)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        // GET: Paciente/Create
        public IActionResult Create()
        {
            ViewData["Medico"] = new SelectList(_context.Medico, "Id", "NombreCompleto");
            return View();
        }

        // POST: Paciente/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NombreCompleto,Sexo,ObraSocial,Edad,telefono,MedicoId")] Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(paciente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MedicoId"] = new SelectList(_context.Set<Medico>(), "Id", "Id", paciente.MedicoId);
            return View(paciente);
        }

        // GET: Paciente/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Paciente == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente.FindAsync(id);
            if (paciente == null)
            {
                return NotFound();
            }
            ViewData["Medico"] = new SelectList(_context.Set<Medico>(), "Id", "NombreCompleto", paciente.MedicoTratante);
            return View(paciente);
        }

        // POST: Paciente/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NombreCompleto,Sexo,ObraSocial,Edad,telefono,MedicoId")] Paciente paciente)
        {
            if (id != paciente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paciente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PacienteExists(paciente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MedicoId"] = new SelectList(_context.Set<Medico>(), "Id", "Id", paciente.MedicoId);
            return View(paciente);
        }

        // GET: Paciente/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Paciente == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente
                .Include(p => p.Medico)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        // POST: Paciente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Paciente == null)
            {
                return Problem("Entity set 'MvcMedicoContext.Paciente'  is null.");
            }
            var paciente = await _context.Paciente.FindAsync(id);
            if (paciente != null)
            {
                _context.Paciente.Remove(paciente);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PacienteExists(int id)
        {
          return (_context.Paciente?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Paciente/Create.cshtml
@model RecepcionMedica.Models.Paciente

@{
    ViewData["Title"] = "Create";
}

<h1 style="text-align:center; font-family: 'Lobster', cursive; font-size: 32px; font-weight: bold;color: #1A5276;">Menu de Alta</h1>

<h4>Nuevo Paciente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreCompleto" class="control-label"></label>
                <input asp-for="NombreCompleto" class="form-control" />
                <span asp-validation-for="NombreCompleto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <select asp-for="Sexo" class="form-control">
                    <option value="0">Femenino</option>
                    <option value="1">Masculino</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ObraSocial" class="control-label"></label>
                <input asp-for="ObraSocial" class="form-control" />
                <span asp-validation-for="ObraSocial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefono" class="control-label"></label>
                <input asp-for="telefono" class="form-control" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
<<<<<<< HEAD
                <label asp-for="MedicoId" class="control-label"></label>
                <select asp-for="MedicoId" class ="form-control" asp-items="ViewBag.MedicoId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
=======
                <label asp-for="Medico" class="control-label"></label>
                <select asp-for="MedicoId" class ="form-control" asp-items="ViewBag.Medico"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Dar de Alta" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-secondary">Volver al Indice</a>
>>>>>>> 5d9bbaa6d9f93df87766794fe5648c83a0e1a581
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Paciente/Delete.cshtml
@model RecepcionMedica.Models.Paciente

@{
    ViewData["Title"] = "Delete";
}

<h1 style="text-align:center; font-family: 'Lobster', cursive; font-size: 32px; font-weight: bold;color: #1A5276;">Esta seguro que desea eliminar el Paciente?</h1>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCompleto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ObraSocial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ObraSocial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medico)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medico.NombreCompleto)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar Paciente" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Volver al Indice</a>
    </form>
</div>

Views/Paciente/Details.cshtml
@model RecepcionMedica.Models.Paciente

@{
    ViewData["Title"] = "Details";
}

<h1 style="text-align:center; font-family: 'Lobster', cursive; font-size: 32px; font-weight: bold;color: #1A5276;">Detalle</h1>

<div>
    <h4>Paciente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCompleto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ObraSocial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ObraSocial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medico)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MedicoTratante)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" class="btn btn-secondary">Volver al Indice</a>
</div>

Views/Paciente/Edit.cshtml
@model RecepcionMedica.Models.Paciente

@{
    ViewData["Title"] = "Edit";
}

<h1 style="text-align:center; font-family: 'Lobster', cursive; font-size: 32px; font-weight: bold;color: #1A5276;">Editar Paciente</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NombreCompleto" class="control-label"></label>
                <input asp-for="NombreCompleto" class="form-control" />
                <span asp-validation-for="NombreCompleto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <select asp-for="Sexo" class="form-control">
                    <option value="0">Femenino</option>
                    <option value="1">Masculino</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ObraSocial" class="control-label"></label>
                <input asp-for="ObraSocial" class="form-control" />
                <span asp-validation-for="ObraSocial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefono" class="control-label"></label>
                <input asp-for="telefono" class="form-control" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medico" class="control-label"></label>
                <select asp-for="MedicoId" class="form-control" asp-items="ViewBag.Medico"></select>
                <span asp-validation-for="MedicoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Volver al Indice</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Paciente/Index.cshtml
@using recepcionMedica.ViewModels;

@model PacienteViewModel;

@{
    ViewData["Title"] = "Index";
}
<head>
    <link rel="stylesheet" href="/css/style.css">
    <style>
    body {
        background-color: #E0FFFF;
    }
</style>
</head>

<h1 style="text-align:center; font-family: 'Lobster', cursive; font-size: 32px; font-weight: bold; color: #1A5276;">Índice de Pacientes</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Dar de alta Nuevo Paciente</a>
</p>

<div class="row">
    <form method="get" asp-action="Index" asp-controller="Paciente">
        <div class="rec form-group">
            <input class ="form-control" asp-for="NameFilter">
        </div>
        <button class="btn btn-secondary" type="submit">Buscar</button>
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pacientes.FirstOrDefault().NombreCompleto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pacientes.FirstOrDefault().Sexo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pacientes.FirstOrDefault().ObraSocial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pacientes.FirstOrDefault().Edad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pacientes.FirstOrDefault().telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pacientes.FirstOrDefault().MedicoTratante)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Pacientes) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCompleto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ObraSocial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MedicoTratante)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>